/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'eu-west-1',
  aws_cognito_identity_pool_id:
    'eu-west-1:e59ae90e-aca4-4c49-b0c9-f3faf4530108',
  aws_cognito_region: 'eu-west-1',
  aws_user_pools_id: 'eu-west-1_f8F2XPlJ2',
  aws_user_pools_web_client_id: '6jf7i42cld7b42c862lkhejiha',
  oauth: {},
  aws_cognito_login_mechanisms: ['EMAIL'],
  aws_cognito_signup_attributes: ['EMAIL'],
  aws_cognito_mfa_configuration: 'OFF',
  aws_cognito_mfa_types: ['SMS'],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
};

export default awsmobile;
